/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/layout/app-header.vue')['default']
    AppSidebar: typeof import('./src/components/layout/app-sidebar.vue')['default']
    BacktestPerformanceChart: typeof import('./src/components/backtest/backtest-performance-chart.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTimePicker: typeof import('element-plus/es')['ElTimePicker']
    FactorScoreCard: typeof import('./src/components/stock-detail/factor-score-card.vue')['default']
    FilterBuilderForm: typeof import('./src/components/screening/filter-builder-form.vue')['default']
    HistoricalResultTable: typeof import('./src/components/backtest/historical-result-table.vue')['default']
    InstitutionalTrendChart: typeof import('./src/components/chip-stats/institutional-trend-chart.vue')['default']
    LlmReportPanel: typeof import('./src/components/stock-detail/llm-report-panel.vue')['default']
    MarginTrendChart: typeof import('./src/components/chip-stats/margin-trend-chart.vue')['default']
    PriceCandlestickChart: typeof import('./src/components/stock-detail/price-candlestick-chart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SchedulerConfigForm: typeof import('./src/components/settings/scheduler-config-form.vue')['default']
    ScreeningResultTable: typeof import('./src/components/screening/screening-result-table.vue')['default']
    SectorFilterTabs: typeof import('./src/components/dashboard/sector-filter-tabs.vue')['default']
    SectorTag: typeof import('./src/components/shared/sector-tag.vue')['default']
    StockRankingTable: typeof import('./src/components/dashboard/stock-ranking-table.vue')['default']
    TechnicalIndicatorChart: typeof import('./src/components/stock-detail/technical-indicator-chart.vue')['default']
    WeightSliderGroup: typeof import('./src/components/settings/weight-slider-group.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
