/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/layout/app-header.vue')['default']
    AppSidebar: typeof import('./src/components/layout/app-sidebar.vue')['default']
    BacktestPerformanceChart: typeof import('./src/components/backtest/backtest-performance-chart.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    FactorScoreCard: typeof import('./src/components/stock-detail/factor-score-card.vue')['default']
    FilterBuilderForm: typeof import('./src/components/screening/filter-builder-form.vue')['default']
    HistoricalResultTable: typeof import('./src/components/backtest/historical-result-table.vue')['default']
    InstitutionalTrendChart: typeof import('./src/components/chip-stats/institutional-trend-chart.vue')['default']
    LlmReportPanel: typeof import('./src/components/stock-detail/llm-report-panel.vue')['default']
    MarginTrendChart: typeof import('./src/components/chip-stats/margin-trend-chart.vue')['default']
    PriceCandlestickChart: typeof import('./src/components/stock-detail/price-candlestick-chart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SchedulerConfigForm: typeof import('./src/components/settings/scheduler-config-form.vue')['default']
    ScreeningResultTable: typeof import('./src/components/screening/screening-result-table.vue')['default']
    ScrollToTop: typeof import('./src/components/shared/scroll-to-top.vue')['default']
    SectorFilterTabs: typeof import('./src/components/dashboard/sector-filter-tabs.vue')['default']
    SectorTag: typeof import('./src/components/shared/sector-tag.vue')['default']
    StockRankingTable: typeof import('./src/components/dashboard/stock-ranking-table.vue')['default']
    TechnicalIndicatorChart: typeof import('./src/components/stock-detail/technical-indicator-chart.vue')['default']
    WeightSliderGroup: typeof import('./src/components/settings/weight-slider-group.vue')['default']
  }
}
